---
# tasks file for haproxy
- block:
    - name: Install applications
      ansible.builtin.package:
        name: "haproxy"
        state: present

    - name: Create external configure files
      ansible.builtin.template:
        src: "haproxy.external.cfg.j2"
        dest: "/etc/haproxy/haproxy.cfg"
      when:
        - inventory_hostname in groups['elb']

    - name: Create internal configure files
      ansible.builtin.template:
        src: "haproxy.internal.cfg.j2"
        dest: "/etc/haproxy/haproxy.cfg"
      when:
        - inventory_hostname in groups['ilb']

    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Start the service
      ansible.builtin.systemd:
        name: haproxy
        enabled: yes
        state: restarted

    # - name: Wait for haproxy
    #   wait_for:
    #     port: "{% if ha is defined and ha.type == 'slb' %}8443{% else %}8081{% endif %}"
    #     delay: 3
    #     state: started
    #     host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
    #   connection: local
    #   when: haproxy_pkg.changed or haproxy_cfg.changed
  when: 
    - ha.type == "slb"
