---
# tasks file for rails
- name: Create configure files
  template:
    src: gitlab.rails.rb.j2
    dest: /etc/gitlab/gitlab.rails.rb
  register: gitlab_rb_file

- name: Distribution gitlab-secrets.json file
  ansible.builtin.copy:
    src: /usr/local/src/gitlab-secrets.json
    dest: /etc/gitlab/gitlab-secrets.json
  register: gitlab_secrets_file

- name: Reconfiugre service
  ansible.builtin.shell: gitlab-ctl reconfigure
  when: gitlab_rb_file.changed or gitlab_secrets_file.changed