---
# tasks file for praefectpg
- name: Create configure files
  template:
    src: gitlab.praefectpg.rb.j2
    dest: /etc/gitlab/gitlab.praefectpg.rb
  register: gitlab_rb_file

- name: Distribution gitlab-secrets.json file
  ansible.builtin.copy:
    src: /usr/local/src/gitlab-secrets.json
    dest: /etc/gitlab/gitlab-secrets.json
  register: gitlab_secrets_file

- name: Reconfiugre service
  shell: gitlab-ctl reconfigure
  when: gitlab_rb_file.changed or gitlab_secrets_file.changed

- name: Check if Database is available for Praefect
  shell: /opt/gitlab/embedded/bin/psql -U gitlab-psql -d template1 -h 127.0.0.1 -c "SELECT 1 FROM pg_roles WHERE rolname='praefect';"
  register: praefect_database_check_result
  retries: 5
  delay: 10
  until: praefect_database_check_result is success

- name: Setup Database on Postgres
  shell: |
    /opt/gitlab/embedded/bin/psql -U gitlab-psql -d template1 -h 127.0.0.1 -c "CREATE ROLE praefect WITH LOGIN CREATEDB PASSWORD '{{ auth.praefectpg.praefect.password }}';"
    /opt/gitlab/embedded/bin/psql -U praefect -d template1 -h 127.0.0.1 -c "CREATE DATABASE praefect_production WITH ENCODING=UTF8;"
  when: "'(0 rows)' in praefect_database_check_result.stdout"
